- name: Generate Traefik dynamic config on host
  hosts: traefik
  become: true


  tasks:
    - name: Validate required vars
      assert:
        that:
          - domains is defined
          - caddy_url is defined
          - apps is defined


    - name: Ensure conf.d exists
      file:
        path: /etc/traefik/conf.d
        state: directory
        owner: root
        group: root
        mode: "0755"


    - name: Render services.yaml directly on Traefik host
      template:
        src: traefik_dynamic.yml.j2
        dest: /etc/traefik/conf.d/services.yaml
        owner: root
        group: root
        mode: "0644"


    - name: Validate Traefik config (opcional)
      command: traefik check-config
      ignore_errors: yes