---
- name: Ensure autofs is configured with required flags
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    desired_flags: "--timeout=60 --ghost"
    backup_suffix: ".bak_{{ ansible_date_time.iso8601_basic_short }}"

  tasks:

    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Set autofs_installed variable
      ansible.builtin.set_fact:
        autofs_installed: "{{ 'autofs' in ansible_facts.packages }}"

    - name: Skip playbook if autofs is not installed
      ansible.builtin.debug:
        msg: "Autofs is not installed. Skipping configuration tasks."
      when: not autofs_installed

    - name: Backup /etc/auto.master before modification
      ansible.builtin.copy:
        src: /etc/auto.master
        dest: "/etc/auto.master{{ backup_suffix }}"
        remote_src: yes
      when: autofs_installed

    - name: Read /etc/auto.master
      ansible.builtin.slurp:
        src: /etc/auto.master
      register: auto_master_content
      when: autofs_installed

    - name: Decode /etc/auto.master content
      ansible.builtin.set_fact:
        auto_master_text: "{{ auto_master_content.content | b64decode }}"
      when: autofs_installed

    - name: Fix flags in /etc/auto.master using Python script
      ansible.builtin.copy:
        dest: /tmp/fix_auto_master.py
        content: |
          import sys
          lines = sys.stdin.read().splitlines()
          for line in lines:
              if line.startswith("#") or not line.strip():
                  print(line)
                  continue
              if "--timeout" not in line:
                  line += " --timeout=60"
              if "--ghost" not in line:
                  line += " --ghost"
              print(line)
      when: autofs_installed

    - name: Generate new_auto_master using Python script
      ansible.builtin.command:
        cmd: python3 /tmp/fix_auto_master.py
        stdin: "{{ auto_master_text }}"
      register: fixed_auto_master
      when: autofs_installed

    - name: Update /etc/auto.master if necessary
      ansible.builtin.copy:
        dest: /etc/auto.master
        content: "{{ fixed_auto_master.stdout }}"
        owner: root
        group: root
        mode: '0644'
      when: autofs_installed and auto_master_text != fixed_auto_master.stdout

    - name: Restart autofs if changes were made
      ansible.builtin.service:
        name: autofs
        state: restarted
      when: autofs_installed and auto_master_text != fixed_auto_master.stdout

    - name: Show result if autofs was installed
      ansible.builtin.debug:
        msg: >-
          /etc/auto.master checked and updated if necessary.
          Backup: /etc/auto.master{{ backup_suffix }}
      when: autofs_installed
